# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Packages
        run: npm i -g pnpm && pnpm i

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-page
          folder: dist
          commit-message: ${{ github.event.head_commit.message }}
